// src/config/SIDE_BAR.ts
// 프롬프트 토큰 사이드바 데이터

export type PromptToken = {
  token: string; // 영어 토큰 (실제 프롬프트에 들어갈 값)
  description: string; // 한글 설명
};

export type Category = {
  id: string;
  name: string; // 대분류 이름
  tokens: PromptToken[];
};

export const SIDE_BAR_CATEGORIES: Category[] = [
  {
    id: "style-mood",
    name: "Style & Mood (스타일 & 무드)",
    tokens: [
      { token: "anime style", description: "애니메이션 스타일" },
      { token: "blockbuster style", description: "블록버스터 영화 같은 거대한 연출 느낌" },
      { token: "coming-of-age", description: "성장물 드라마 같은 분위기" },
      { token: "cosmic horror", description: "우주적 공포, 이해 불가능한 존재의 공포감" },
      { token: "cyber-noir", description: "사이버 세계와 필름 누아르가 섞인 어두운 분위기" },
      { token: "cyberpunk", description: "네온 도시와 미래 범죄 세계관의 사이버펑크" },
      { token: "dark and moody", description: "조명과 분위기가 어둡고 우울한 느낌" },
      { token: "dark fantasy", description: "잔혹하고 어두운 판타지 세계관" },
      { token: "dieselpunk", description: "디젤 엔진 시대 감성의 레트로 미래 세계관" },
      { token: "disney style", description: "디즈니 애니메이션 같은 밝고 동화적인 스타일" },
      { token: "dreamy", description: "몽환적이고 흐릿한 꿈속 같은 분위기" },
      { token: "editorial", description: "패션 매거진 화보 같은 연출 스타일" },
      { token: "epic", description: "엄청난 스케일과 장엄한 분위기" },
      { token: "fantasy", description: "전형적인 판타지 세계관 느낌" },
      { token: "fantastical", description: "현실에서는 불가능한 상상 가득한 느낌" },
      { token: "film noir", description: "흑백 누아르 영화 같은 강한 명암과 범죄 분위기" },
      { token: "film still", description: "영화에서 캡처한 한 장면 같은 느낌" },
      { token: "found footage vibe", description: "발견된 캠코더 영상 같은 리얼한 공포 분위기" },
      { token: "ghibli-inspired style", description: "지브리 애니메이션 감성" },
      { token: "gothic horror", description: "고딕 건축과 어두운 공포가 섞인 분위기" },
      { token: "hard sci-fi", description: "과학 설정이 디테일한 하드 SF 느낌" },
      { token: "heroic fantasy", description: "영웅이 활약하는 밝은 판타지 세계" },
      { token: "high drama", description: "감정과 갈등이 극단적으로 강조된 분위기" },
      { token: "high fashion", description: "하이패션 런웨이와 잡지 느낌" },
      { token: "hollywood style", description: "헐리우드 상업 영화 같은 스타일" },
      { token: "hyperrealistic", description: "사진보다 더 현실적인 초사실 표현" },
      { token: "intimidating", description: "위협적이고 압박감을 주는 분위기" },
      { token: "korean drama style", description: "한국 드라마 연출과 색감 느낌" },
      { token: "k-pop music video style", description: "K-POP 뮤직비디오 같은 화려한 연출" },
      { token: "manga style", description: "흑백 만화 같은 선과 톤 느낌" },
      { token: "mecha sci-fi", description: "거대한 로봇과 미래 전쟁이 나오는 SF 스타일" },
      { token: "melancholic", description: "쓸쓸하고 서글픈 분위기" },
      { token: "movie still", description: "영화 스틸컷 같은 한 장면" },
      { token: "mysterious", description: "정체를 알 수 없는 수수께끼 분위기" },
      { token: "neo-noir", description: "현대적인 색감으로 재해석한 누아르 느낌" },
      { token: "noir", description: "그림자와 범죄가 강조된 누아르 분위기" },
      { token: "nostalgic", description: "옛 추억을 떠올리게 하는 향수 가득한 느낌" },
      { token: "photorealistic", description: "사진처럼 사실적인 렌더링" },
      { token: "playful", description: "장난스럽고 밝은 분위기" },
      { token: "pixar style", description: "픽사 애니메이션 같은 3D 캐릭터 감성" },
      { token: "psychological horror", description: "심리적인 압박과 불안감 중심의 공포" },
      { token: "realistic", description: "과장 없이 현실에 가까운 표현" },
      { token: "romantic", description: "사랑과 설렘이 느껴지는 분위기" },
      { token: "serene", description: "고요하고 평화로운 분위기" },
      { token: "slice-of-life", description: "일상의 한 조각을 담은 편안한 느낌" },
      { token: "slasher horror", description: "살인마가 나오는 직접적 공포 연출" },
      { token: "solarpunk", description: "태양 에너지와 친환경 미래 도시 감성" },
      { token: "space opera", description: "우주 전쟁과 영웅 서사가 있는 대서사 SF" },
      { token: "steampunk", description: "증기기관과 빅토리아풍 기계 장치 스타일" },
      { token: "surreal", description: "꿈과 같은 초현실적인 표현" },
      { token: "techno-thriller", description: "기술과 스릴러가 결합된 긴장감 있는 분위기" },
      { token: "tense atmosphere", description: "공기가 팽팽하게 긴장된 느낌" },
      { token: "terrifying", description: "보는 것만으로 무서운 공포 분위기" },
      { token: "triumphant", description: "승리와 성취감이 폭발하는 장면 느낌" },
      { token: "ultra cinematic", description: "영화관 스크린용 초영화적 연출" },
      { token: "vogue style", description: "Vogue 잡지 화보 같은 세련된 사진 스타일" },
      { token: "webtoon style", description: "컬러 웹툰 같은 선과 색감" },
      { token: "whimsical", description: "엉뚱하고 동화 같은 귀여운 분위기" },
      { token: "y2k aesthetic", description: "2000년대 초반 인터넷·게임 감성" },
      { token: "vaporwave aesthetic", description: "복고 디지털 감성과 네온 컬러 조합" },
      { token: "synthwave aesthetic", description: "레트로 SF와 신시사이저 음악 감성" },
      { token: "dark academia aesthetic", description: "고전 책과 대학 분위기의 어두운 지성 미학" },
      { token: "cottagecore aesthetic", description: "시골 생활과 자연을 동경하는 힐링 감성" },
      { token: "eerie", description: "기묘하고 소름 돋는 분위기" },
      { token: "hopeful", description: "희망이 느껴지는 따뜻한 분위기" },
      { token: "dramatic", description: "강한 감정 변화와 과장된 연출" },
      { token: "cinematic", description: "전체적으로 영화 장면 같은 느낌" },
    ],
  },
  {
    id: "scene-type",
    name: "Scene Type & Situation (장면 타입 & 상황)",
    tokens: [
      { token: "action scene", description: "격투와 폭발이 있는 액션 장면" },
      { token: "aftermath scene", description: "사건이 끝난 뒤의 잔해와 여운 장면" },
      { token: "battle scene", description: "군대나 집단이 맞붙는 전투 장면" },
      { token: "chase scene", description: "도망과 추격이 이어지는 장면" },
      { token: "cityscape", description: "도시 전체를 보여주는 장면" },
      { token: "dream sequence", description: "꿈속에서 일어나는 비현실 장면" },
      { token: "documentary style", description: "다큐멘터리 촬영 같은 리얼한 장면" },
      { token: "emotional close-up", description: "감정을 집중적으로 보여주는 클로즈업" },
      { token: "epic landscape", description: "웅장한 자연 풍경 장면" },
      { token: "establishing shot", description: "장소를 소개하는 와이드 샷" },
      { token: "explosion scene", description: "폭발이 중심이 되는 장면" },
      { token: "fight scene", description: "두 인물이 격투하는 장면" },
      { token: "final boss confrontation", description: "최종 보스와 맞서는 클라이맥스 장면" },
      { token: "full body shot", description: "머리부터 발끝까지 전신이 보이는 장면" },
      { token: "group shot", description: "여러 명이 함께 등장하는 장면" },
      { token: "interior scene", description: "실내 공간에서 벌어지는 장면" },
      { token: "impact moment", description: "무언가 부딪히는 바로 그 순간" },
      { token: "just before impact", description: "충돌 직전 긴장감이 최고조인 순간" },
      { token: "landscape", description: "자연이나 배경 위주의 풍경 장면" },
      { token: "mid-action", description: "동작 중간이 강조된 장면" },
      { token: "mid-air", description: "공중에 떠 있는 순간을 포착한 장면" },
      { token: "nightmare sequence", description: "악몽 속 공포 장면" },
      { token: "portrait", description: "한 인물의 상반신이나 얼굴 위주 장면" },
      { token: "character portrait", description: "캐릭터 디자인을 보여주는 초상 장면" },
      { token: "pre-battle tension", description: "전투 전에 조용하지만 긴장감 도는 장면" },
      { token: "quiet before the storm", description: "큰 사건 전에 찾아오는 비정상적으로 평온한 장면" },
      { token: "street photography", description: "거리의 순간을 포착한 다큐 느낌 장면" },
      { token: "transformation scene", description: "변신이나 각성 순간을 보여주는 장면" },
      { token: "victory moment", description: "승리 후 환호하는 순간" },
      { token: "war zone", description: "전쟁터 한복판을 담은 장면" },
      { token: "dramatic close-up", description: "감정이 폭발하는 극적인 클로즈업" },
    ],
  },
  {
    id: "character",
    name: "Character & Anatomy (캐릭터 & 인체)",
    tokens: [
      { token: "calm expression", description: "표정이 차분하고 안정된 모습" },
      { token: "cinematic armor", description: "영화 소품 같은 멋진 갑옷 디자인" },
      { token: "confident stance", description: "자신감 넘치는 서 있는 자세" },
      { token: "detailed hands", description: "손가락 주름과 관절까지 세밀한 표현" },
      { token: "detailed skin pores", description: "피부 모공까지 보이는 디테일" },
      { token: "dynamic gesture", description: "팔·손 움직임이 살아 있는 제스처" },
      { token: "dynamic pose", description: "몸 전체가 살아 있는 역동적인 포즈" },
      { token: "dramatic expression", description: "크게 과장된 감정 표현" },
      { token: "expressive hands", description: "손동작만으로 감정이 드러나는 표현" },
      { token: "fierce gaze", description: "눈빛이 날카롭고 강렬한 시선" },
      { token: "flowing hair", description: "바람에 흩날리는 머리카락 표현" },
      { token: "freckles", description: "주근깨가 보이는 피부 표현" },
      { token: "glossy skin", description: "윤기가 흐르는 광택 피부" },
      { token: "heroic pose", description: "영웅이 포즈를 취한 듯한 당당한 자세" },
      { token: "high fashion outfit", description: "패션쇼에 나올 법한 의상" },
      { token: "intense expression", description: "집중과 분노가 섞인 강렬한 표정" },
      { token: "motion blur on hair", description: "머리카락에 모션 블러가 들어간 표현" },
      { token: "natural body proportions", description: "현실적인 신체 비율" },
      { token: "natural pose", description: "부자연스럽지 않은 편안한 자세" },
      { token: "perfect skin", description: "잡티 없는 매끈한 피부" },
      { token: "realistic anatomy", description: "근육과 뼈 구조가 설득력 있는 인체" },
      { token: "streetwear", description: "스트리트 패션 스타일 의상" },
      { token: "strong silhouette", description: "실루엣만 봐도 형태가 또렷한 캐릭터" },
      { token: "subtle expression", description: "눈·입만 살짝 달라지는 미세한 표정" },
      { token: "tactical gear", description: "전술 조끼, 방탄복 같은 전투 장비 의상" },
      { token: "wet skin", description: "물에 젖어 반짝이는 피부" },
      { token: "wind in hair", description: "바람 때문에 머리가 크게 휘날리는 모습" },
      { token: "action pose", description: "점프·공격 같은 액션 포즈" },
      { token: "futuristic armor", description: "SF 영화에 나올 법한 미래형 갑옷" },
      { token: "subject", description: "프레임에서 주 피사체를 강조하는 키워드" },
    ],
  },
  {
    id: "camera",
    name: "Camera & Lens (카메라 & 렌즈)",
    tokens: [
      { token: "shot on 35mm film", description: "35mm 필름 카메라로 찍은 듯한 질감" },
      { token: "shot on DSLR", description: "DSLR 카메라로 촬영한 느낌" },
      { token: "shot on mirrorless", description: "미러리스 카메라 느낌" },
      { token: "shot on RED camera", description: "RED 시네마 카메라로 촬영한 영화 느낌" },
      { token: "shot on ARRI Alexa", description: "ARRI Alexa로 찍은 고급 시네마 룩" },
      { token: "shot on IMAX 70mm", description: "IMAX 70mm 필름 같은 초고해상 영화 느낌" },
      { token: "handheld shot", description: "손으로 들고 찍은 흔들림 있는 샷" },
      { token: "stabilized shot", description: "짐벌·스테디캠으로 안정화된 샷" },
      { token: "24mm lens", description: "넓은 화각의 24mm 광각 렌즈 느낌" },
      { token: "35mm lens", description: "자연스러운 시야각의 35mm 표준 렌즈 느낌" },
      { token: "50mm lens", description: "클래식 인물 촬영용 50mm 렌즈 느낌" },
      { token: "85mm lens", description: "압축된 인물 화각의 85mm 망원 렌즈 느낌" },
      { token: "macro lens", description: "작은 물체를 크게 잡는 매크로 렌즈 느낌" },
      { token: "fisheye lens", description: "왜곡이 심한 어안 렌즈 느낌" },
      { token: "tilt-shift lens", description: "미니어처 효과가 나는 틸트시프트 렌즈 느낌" },
      { token: "close-up", description: "얼굴이나 디테일을 크게 잡는 클로즈업" },
      { token: "extreme close-up", description: "눈·입 같은 부분만 크게 잡는 극단 클로즈업" },
      { token: "medium shot", description: "가슴이나 허리 정도까지 나오는 미디엄 샷" },
      { token: "wide shot", description: "전체 장면을 넓게 보여주는 와이드 샷" },
      { token: "panoramic shot", description: "수평으로 길게 이어진 파노라마 샷" },
      { token: "POV shot", description: "캐릭터 시점에서 보는 1인칭 샷" },
      { token: "over-the-shoulder shot", description: "어깨 너머로 상대를 보는 샷" },
      { token: "centered shot", description: "피사체가 화면 중앙에 오는 샷" },
      { token: "top-down shot", description: "위에서 아래로 내려다보는 샷" },
      { token: "high angle shot", description: "위에서 아래를 내려다보는 높은 앵글" },
      { token: "low angle shot", description: "아래에서 위를 올려다보는 낮은 앵글" },
      { token: "drone shot", description: "공중에서 내려다보는 드론 촬영 느낌" },
      { token: "dutch angle", description: "프레임이 기울어진 불안한 느낌의 샷" },
      { token: "bird's-eye view", description: "새가 하늘에서 내려다보는 것 같은 시점" },
      { token: "f/1.2", description: "아주 얕은 심도로 배경이 크게 날아가는 조리개" },
      { token: "f/1.4", description: "강한 아웃포커싱이 걸리는 조리개" },
      { token: "f/1.8", description: "인물 촬영에 많이 쓰는 얕은 심도 조리개" },
      { token: "f/2.8", description: "배경 흐림과 선명함이 균형 잡힌 조리개" },
      { token: "f/8", description: "전체가 또렷하게 보이는 조리개" },
      { token: "shallow depth of field", description: "배경이 크게 흐려지는 얕은 심도" },
      { token: "deep depth of field", description: "앞뒤가 모두 선명한 깊은 심도" },
      { token: "creamy bokeh", description: "배경 빛망울이 부드럽게 녹아내리는 보케" },
      { token: "anamorphic bokeh", description: "가로로 늘어난 아나몰픽 보케" },
      { token: "subject in sharp focus", description: "피사체만 매우 또렷한 초점" },
      { token: "depth of field", description: "심도 표현 자체를 강조하는 키워드" },
    ],
  },
  {
    id: "lighting",
    name: "Lighting & Lens FX (조명 & 렌즈 효과)",
    tokens: [
      { token: "backlighting", description: "피사체 뒤에서 비춰 실루엣을 만드는 역광" },
      { token: "blue hour lighting", description: "해 뜨기 전·해 진 직후의 푸른 시간대 조명" },
      { token: "cinematic lighting", description: "영화 촬영처럼 계산된 조명 연출" },
      { token: "chromatic aberration", description: "색수차가 생긴 렌즈 오류 느낌" },
      { token: "dramatic lighting", description: "명암 대비가 강한 극적인 조명" },
      { token: "film burn", description: "필름이 타들어간 것 같은 빛 번짐" },
      { token: "god rays", description: "구름 사이로 내려오는 빛기둥 표현" },
      { token: "golden hour lighting", description: "노을 지는 시간대의 따뜻한 조명" },
      { token: "high-key lighting", description: "어두운 부분이 거의 없는 밝은 조명" },
      { token: "lens flare", description: "빛이 렌즈에 반사되어 생기는 플레어" },
      { token: "light leak", description: "필름 가장자리로 빛이 새어 들어온 느낌" },
      { token: "low-key lighting", description: "어둠이 전체를 지배하는 저조도 조명" },
      { token: "moonlight", description: "달빛에 의해 비춰지는 차분한 조명" },
      { token: "moody lighting", description: "그림자와 명암을 강조한 분위기 조명" },
      { token: "natural lighting", description: "인공 조명 없이 자연광만 사용한 느낌" },
      { token: "neon lighting", description: "네온사인에서 나오는 컬러풀한 빛" },
      { token: "rim lighting", description: "피사체 윤곽만 빛으로 둘러싸는 조명" },
      { token: "soft bloom", description: "밝은 부분이 살짝 번지는 부드러운 빛 번짐" },
      { token: "soft natural light", description: "창가 같은 부드러운 자연광" },
      { token: "studio lighting", description: "사진 스튜디오 조명 세팅 느낌" },
      { token: "sunset lighting", description: "해 질 때의 주황빛 조명" },
      { token: "three-point lighting", description: "키·필·백 세 가지 조명 구성을 활용한 연출" },
      { token: "uplight", description: "아래에서 위로 비추는 조명" },
      { token: "vignetting", description: "프레임 가장자리가 어두워지는 비네팅 효과" },
      { token: "volumetric lighting", description: "공기 중 먼지가 보이는 입체적인 빛줄기" },
      { token: "anamorphic lens flare", description: "가로로 긴 아나몰픽 플레어" },
      { token: "softbox lighting", description: "소프트박스로 만든 부드러운 그림자 조명" },
      { token: "accent lighting", description: "특정 부분만 강조해서 비추는 포인트 조명" },
      { token: "global illumination", description: "장면 전체에 빛이 간접 반사되는 사실적인 조명" },
    ],
  },
  {
    id: "detail",
    name: "Detail, Quality & Resolution (디테일 · 퀄리티 · 해상도)",
    tokens: [
      { token: "4k", description: "4K 수준의 고해상도 느낌" },
      { token: "8k", description: "8K 수준의 초고해상도 느낌" },
      { token: "clear features", description: "눈·코·입 윤곽이 아주 또렷한 표현" },
      { token: "cinematic grading", description: "영화 컬러 그레이딩 느낌" },
      { token: "cross processing", description: "필름을 다른 화학 처리로 현상한 특이한 색감" },
      { token: "crushed blacks", description: "어두운 부분이 완전히 눌려 검게 뭉친 톤" },
      { token: "film emulation", description: "특정 필름을 모방한 색감" },
      { token: "flawless", description: "흠잡을 곳 없이 매끈한 퀄리티" },
      { token: "HDR", description: "밝은 곳과 어두운 곳 모두 살아 있는 높은 명암비 표현" },
      { token: "high contrast editing", description: "명암 대비를 강하게 올린 편집 스타일" },
      { token: "high resolution", description: "픽셀이 보이지 않는 선명한 해상도" },
      { token: "highly detailed", description: "디테일 요소가 매우 많은 표현" },
      { token: "insanely detailed", description: "말도 안 되게 과한 수준의 디테일" },
      { token: "intricate details", description: "복잡한 문양과 장식이 가득한 디테일" },
      { token: "lifted blacks", description: "검은색을 살짝 올려서 부드럽게 만든 톤" },
      { token: "matte finish grading", description: "광택이 없는 무광 느낌 색보정" },
      { token: "polished", description: "전반적으로 잘 다듬어진 깔끔한 마감" },
      { token: "sharp details", description: "선과 질감이 칼같이 또렷한 디테일" },
      { token: "soft contrast editing", description: "대비를 낮춰 부드럽게 만든 편집" },
      { token: "soft glow effect", description: "전체적으로 은은한 빛이 도는 글로우 효과" },
      { token: "ultra detailed", description: "초고디테일 표현" },
      { token: "ultra high resolution", description: "극도로 높은 해상도 표현" },
      { token: "washed-out colors", description: "색이 바랜 것 같은 흐릿한 색감" },
      { token: "luxurious", description: "고급스럽고 비싼 느낌의 퀄리티" },
      { token: "elegant", description: "우아하고 세련된 마감 느낌" },
      { token: "sharpened details", description: "샤프닝이 강하게 들어간 디테일" },
      { token: "22 megapixels", description: "고화소 DSLR 카메라급 디테일" },
      { token: "perfection", description: "완벽함을 목표로 한 퀄리티 강조 키워드" },
      { token: "shimmering", description: "표면이 반짝반짝 빛나는 느낌" },
      { token: "detailed", description: "디테일이 잘 살아 있는 표현" },
    ],
  },
  {
    id: "color",
    name: "Color & Look (색감 & 룩)",
    tokens: [
      { token: "black and white", description: "완전 흑백 모노톤" },
      { token: "cool tones", description: "푸른 계열이 강한 차가운 색조" },
      { token: "delicate", description: "섬세하고 부드러운 전체 톤" },
      { token: "desaturated", description: "채도가 낮은 흐릿한 색감" },
      { token: "glossy", description: "표면이 매끈하고 반사되는 광택 느낌" },
      { token: "gritty", description: "거칠고 현실적인 질감과 색감" },
      { token: "high contrast", description: "밝고 어두움의 차이가 큰 색감" },
      { token: "iridescent colors", description: "각도에 따라 바뀌는 무지개빛 색감" },
      { token: "jagged", description: "거칠고 날카로운 느낌의 시각적 텍스처" },
      { token: "luminous", description: "자체 발광하는 듯한 빛나는 색감" },
      { token: "majestic", description: "장엄하고 위엄 있는 색감 분위기" },
      { token: "muted colors", description: "톤이 눌린 차분한 색감" },
      { token: "neon colors", description: "형광 네온사인 같은 강렬한 색" },
      { token: "ominous", description: "불길하고 위협적인 색감" },
      { token: "organic", description: "자연 재질과 잘 어울리는 색감" },
      { token: "soft pastel colors", description: "파스텔톤의 부드러운 색감" },
      { token: "rich colors", description: "컬러가 깊고 풍부한 느낌" },
      { token: "saturated colors", description: "채도가 매우 높은 선명한 색감" },
      { token: "subdued colors", description: "튀지 않고 조용한 색감" },
      { token: "teal and orange color grading", description: "틸·오렌지 조합의 시네마 색보정" },
      { token: "translucent", description: "빛이 살짝 통과하는 반투명 느낌" },
      { token: "velvety", description: "벨벳 천처럼 부드럽고 깊은 색감" },
      { token: "vibrant colors", description: "생동감 넘치는 화려한 색감" },
      { token: "vivid colors", description: "눈에 꽂히는 강렬한 색감" },
      { token: "warm tones", description: "노랑·주황 위주의 따뜻한 색조" },
      { token: "geometric", description: "기하학적 패턴이 강조된 비주얼 느낌" },
      { token: "mechanical", description: "기계적인 느낌의 차가운 비주얼" },
    ],
  },
  {
    id: "environment",
    name: "Environment & Atmosphere (환경 & 분위기)",
    tokens: [
      { token: "abandoned building", description: "버려진 건물 내부나 외관" },
      { token: "abandoned theme park", description: "사람이 떠난 폐놀이공원" },
      { token: "ancient ruins", description: "무너진 고대 유적지" },
      { token: "amusement park", description: "활기찬 놀이공원" },
      { token: "classroom interior", description: "학교 교실 내부" },
      { token: "cliff edge", description: "절벽 끝자락 위치" },
      { token: "cozy cafe interior", description: "아늑한 카페 실내" },
      { token: "crowded street", description: "사람이 가득한 번화가 거리" },
      { token: "deep ocean", description: "햇빛이 닿지 않는 깊은 바다" },
      { token: "dense fog", description: "시야를 가리는 짙은 안개" },
      { token: "dust particles", description: "공기 중에 떠 있는 먼지 표현" },
      { token: "empty street", description: "사람이 전혀 없는 거리" },
      { token: "enchanted forest", description: "마법이 있을 것 같은 신비로운 숲" },
      { token: "festival lights", description: "축제 조명으로 가득한 거리" },
      { token: "film grain", description: "필름 사진 같은 입자감" },
      { token: "gentle snowfall", description: "조용히 내리는 눈" },
      { token: "haunted forest", description: "귀신이 나올 것 같은 음산한 숲" },
      { token: "japanese street", description: "일본 도시 거리 풍경" },
      { token: "korean traditional house", description: "한옥 마당과 건물" },
      { token: "lakeside at dusk", description: "해질녘 호숫가 풍경" },
      { token: "light fog", description: "살짝 낀 옅은 안개" },
      { token: "luxury penthouse", description: "고급 펜트하우스 실내" },
      { token: "medieval town", description: "중세 유럽풍 마을" },
      { token: "mountain peak", description: "산 정상 전망" },
      { token: "neon street", description: "네온사인이 가득한 야간 거리" },
      { token: "office interior", description: "현대적인 사무실 내부" },
      { token: "post-apocalyptic city", description: "문명이 무너진 이후의 폐허 도시" },
      { token: "rainy night", description: "비 내리는 밤거리" },
      { token: "rooftop at night", description: "야경이 보이는 옥상" },
      { token: "ruined city", description: "파괴된 도시 풍경" },
      { token: "snowstorm", description: "눈보라 치는 거친 날씨" },
      { token: "space station corridor", description: "우주정거장 복도 내부" },
      { token: "spaceship interior", description: "우주선 내부 구조" },
      { token: "stormy sky", description: "먹구름과 번개가 있는 하늘" },
      { token: "subway station", description: "지하철역 플랫폼" },
      { token: "train interior", description: "기차 객실 내부" },
      { token: "underwater scene", description: "물속에서 본 풍경" },
      { token: "wet surfaces", description: "비나 물로 젖은 바닥과 벽" },
    ],
  },
  {
    id: "time-culture",
    name: "Time & Culture (시간대 & 문화 · 시대)",
    tokens: [
      { token: "prehistoric era", description: "선사 시대 배경" },
      { token: "ancient era", description: "고대 문명 시대" },
      { token: "medieval era", description: "중세 유럽 시대" },
      { token: "victorian era", description: "빅토리아 시대 분위기" },
      { token: "industrial era", description: "산업혁명이 한창인 시대" },
      { token: "modern day", description: "현재와 비슷한 현대 배경" },
      { token: "early 2000s style", description: "2000년대 초반 패션과 감성" },
      { token: "1920s style", description: "플래퍼 드레스와 재즈 시대 분위기" },
      { token: "1950s style", description: "클래식 자동차와 올드 아메리칸 감성" },
      { token: "1980s style", description: "네온과 아케이드 문화의 80년대 감성" },
      { token: "1990s style", description: "카세트, CRT, 초기 인터넷 시대 감성" },
      { token: "near future", description: "가까운 미래 세계관" },
      { token: "distant future", description: "아주 먼 미래의 SF 세계관" },
      { token: "post-apocalyptic future", description: "종말 이후 살아남은 세계" },
      { token: "retro-futurism", description: "옛날 사람들이 상상한 미래 디자인" },
      { token: "solarpunk culture", description: "친환경 에너지와 자연이 조화된 문화" },
      { token: "cottagecore aesthetic", description: "시골 집과 자연 속 삶을 동경하는 문화 감성" },
    ],
  },
  {
    id: "media",
    name: "Media / Film / Art Style (매체 · 필름 · 화풍)",
    tokens: [
      { token: "35mm film", description: "35mm 필름 특유의 질감" },
      { token: "analog film", description: "옛 아날로그 필름 느낌" },
      { token: "film photography", description: "필름 카메라로 찍은 사진 같은 느낌" },
      { token: "kodak portra style", description: "Kodak Portra 필름 색감" },
      { token: "kodak gold style", description: "Kodak Gold 필름 색감" },
      { token: "fuji film style", description: "후지 필름 특유의 색감" },
      { token: "vintage photo", description: "오래된 사진처럼 바랜 느낌" },
      { token: "retro photo", description: "과거 시절 감성의 레트로 사진 스타일" },
      { token: "polaroid style", description: "폴라로이드 인화 사진 느낌" },
    ],
  },
  {
    id: "composition",
    name: "Composition & Perspective (구도 & 시점)",
    tokens: [
      { token: "centered composition", description: "피사체를 화면 중앙에 배치한 구도" },
      { token: "dynamic composition", description: "대각선과 움직임이 느껴지는 구도" },
      { token: "leading lines", description: "시선을 한 지점으로 유도하는 선 구도" },
      { token: "negative space", description: "여백을 크게 활용한 미니멀 구도" },
      { token: "perspective", description: "원근감이 강하게 느껴지는 구도" },
      { token: "rule of thirds composition", description: "삼분할선에 피사체를 배치한 구도" },
      { token: "symmetrical composition", description: "좌우 또는 상하가 대칭인 구도" },
      { token: "wide angle perspective", description: "광각 렌즈 특유의 과장된 원근감" },
    ],
  },
  {
    id: "usage",
    name: "Usage & Output (사용 목적 & 결과물 형태)",
    tokens: [
      { token: "book cover", description: "책 표지용 이미지" },
      { token: "cover art", description: "앨범이나 프로젝트 표지용 아트" },
      { token: "key visual", description: "브랜드나 작품을 대표하는 메인 비주얼" },
      { token: "light novel cover", description: "라이트노벨 표지용 일러스트" },
      { token: "mobile wallpaper", description: "스마트폰 배경화면용 비율 이미지" },
      { token: "poster art", description: "포스터 인쇄를 위한 아트워크" },
      { token: "splash art", description: "게임·콘텐츠 메인 일러스트" },
      { token: "streaming thumbnail", description: "스트리밍 플랫폼 썸네일용" },
      { token: "thumbnail image", description: "유튜브 등 썸네일에 최적화된 이미지" },
      { token: "wallpaper", description: "PC·태블릿 배경화면용 이미지" },
    ],
  },
  {
    id: "negative",
    name: "Negative & Cleanup (네거티브 & 정리용)",
    tokens: [
      { token: "text", description: "이미지 안의 글자를 제거하고 싶을 때" },
      { token: "logo", description: "브랜드 로고 요소를 제거하고 싶을 때" },
      { token: "watermark", description: "워터마크 흔적을 제거하고 싶을 때" },
      { token: "border", description: "사진 테두리 라인을 제거하고 싶을 때" },
      { token: "frame", description: "액자나 프레임 형태를 제거하고 싶을 때" },
      { token: "blur", description: "의도치 않은 흐림 효과를 줄이고 싶을 때" },
      { token: "grain", description: "필름 그레인이나 잡티를 줄이고 싶을 때" },
      { token: "noise", description: "디지털 노이즈를 제거하고 싶을 때" },
      { token: "clutter", description: "배경의 복잡한 군더더기를 정리하고 싶을 때" },
    ],
  },
];

